#!/bin/bash
#PBS -N pet_dpp
#PBS -l nodes=1:ppn=5
#PBS -l walltime=500:00:00
#PBS -l pmem=2gb
#PBS -M sebastian.duchene@sydney.edu.au
#PBS -m abe
#PBS -o pet_dpp.stdout
#PBS -e pet_dpp.stderr
#PBS -P RDS-FSC-VirusRates-RW

# Print the default PBS server
echo PBS default server is $PBS_DEFAULT
# Print the job's working directory and enter it.
echo Working directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
 
# Print some other environment information
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo This jobs runs on the following processors:
NODES=`cat $PBS_NODEFILE`
echo $NODES
# Compute the number of processorsNPROCS=`wc -l < $PBS_NODEFILE`
echo This job has allocated $NPROCS nodes

../mrbayes-3.2.5/src/mb Petterson_aa.nexus




